version: "3"

services:
  database:
    image: postgres
    container_name: Fitness-Database
    ports:
      - 5430:5432
    environment:
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=db
      - POSTGRES_DB=db
